imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: semi_automated.yml }
    - { resource: tools.yml }
    - { resource: version.yml }
    - { resource: table_map.yml, ignore_errors: true }
    - { resource: assessments.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        # handler_id:  session.handler.native_file
        handler_id: ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    cache:
        app: "cache.adapter.%cache.adapter%"
        default_redis_provider: snc_redis.default

# Redis configuration.
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%cache.redis_dsn%"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        version:       '%app.version%'
        noticeDisplay: '%app.noticeDisplay%'
        noticeStyle:   '%app.noticeStyle%'
        noticeText:    '%app.noticeText%'


# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            meta:
                driver:   pdo_mysql
                host:     "%database_replica_host%"
                port:     "%database_replica_port%"
                dbname:   "%database_meta_name%"
                user:     "%database_replica_user%"
                password: "%database_replica_password%"
                charset:  UTF8
            replicas:
                driver:   pdo_mysql
                host:     "%database_replica_host%"
                port:     "%database_replica_port%"
                dbname:   "%database_replica_name%"
                user:     "%database_replica_user%"
                password: "%database_replica_password%"
                charset:  UTF8
            toolsdb:
                driver:   pdo_mysql
                host:     "%database_toolsdb_host%"
                port:     "%database_toolsdb_port%"
                dbname:   "%database_toolsdb_name%"
                user:     "%database_replica_user%"
                password: "%database_replica_password%"
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
            meta:
                connection: meta
            replicas:
                connection: replicas
            toolsdb:
                connection: toolsdb

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
            apply_to:  '\.scss$'

# Nelmio CORS Configuration
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST']
        max_age: 3600
        hosts: []
        origin_regex: false

# FOSRest Configuration
fos_rest:
    zone:
        - { path: ^/api/* }
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true

hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [secured_area]

    # an optional setting to configure a query string parameter which can be used to redirect
    # the user after authentication, e.g. /connect/facebook?_destination=/my/destination will
    # redirect the user to /my/destination after facebook authenticates them.  If this is not
    # set then the user will be redirected to the original resource that they requested, or
    # the base address if no resource was requested.  This is similar to the behaviour of
    # [target_path_parameter for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html).
    # target_path_parameter: _destination

    # an optional setting to use the HTTP REFERER header to be used in case no
    # previous URL was stored in the session (i.e. no resource was requested).
    # This is similar to the behaviour of
    # [using the referring URL for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html#using-the-referring-url).
    # use_referer: true

    # here you will add one (or more) configurations for resource owners
    resource_owners:
            wmf:
                type:                oauth2
                client_id:           "%oauth_id%"
                client_secret:       "%oauth_secret%"
                access_token_url:    https://deployment.wikimedia.beta.wmflabs.org/w/index.php?title=Special:OAuth/token
                authorization_url:   https://deployment.wikimedia.beta.wmflabs.org/w/index.php?title=Special:OAuth/authorize
                infos_url:           https://deployment.wikimedia.beta.wmflabs.org/w/index.php?title=Special:OAuth/user
                scope:               "read"
                user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
                paths:
                    identifier: id
                    nickname:   username
                    realname:   fullname